### ISSUE TITLE
Roadmap verze 0.3.

### ISSUE THREAD

**Issue by alesvomacka** [stem-cz/stemtools#1]
# Verze 0.1.

- [ ]  Konzistentní syntax a názvy argumentů všech funkcí pro vytváření grafů.
- [ ] Sára-style verze funkcí pro vytváření grafů.
- [ ] Funkce pro zobrazení baterie položek pomocí facet.
- [ ] Barevné škály (legacy škály Stemu, alespoň jedna nominální a jedna sekvenční).
- [ ] Vignette pro vytváření grafů včetně příkladů
- [ ] Nálepka

# Verze 0.2

- [ ] Quarto template pro Powerpoint a Word.
- [ ] Export grafů pomocí Officer do křivek.
- [ ] Funkce pro výpočet škál.
- [ ]  Funkce pro iterativní vážení.
